// <auto-generated />
namespace SnakeMiro.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.3.0")]
    public sealed partial class Vytvorenie_databazy : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Vytvorenie_databazy));
        
        string IMigrationMetadata.Id
        {
            get { return "201911241816157_Vytvorenie_databazy"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
